### ISSUE TITLE
java style variable

### ISSUE THREAD

**Issue by Bazma** [heba-khazbak/FCI-CS352-CS_2#4]
The function saveHashtag in Class Hashtag its problem is:  There is no Java Coding Style (variables names(String IDs))and there is a variable don’t have good names(ret).

**Comment by ZiadMohamed** [comment]
"IDs" is plural for "ID". The word "IDs" is used in class "Post" and  in table "Post", so I couldn't find any better name for that variable.

The variable "ret" was short for "returnedValue" but I fixed it anyway, thanks.
